# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogPython', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='envoi',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='lu',
            field=models.BooleanField(default=False),
        ),
    ]
