# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPython', '0004_auto_20170517_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(to='blogPython.Categorie'),
        ),
    ]
