# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogPython', '0005_article_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categarticle',
            name='article',
        ),
        migrations.RemoveField(
            model_name='categarticle',
            name='categorie',
        ),
        migrations.DeleteModel(
            name='CategArticle',
        ),
    ]
